### ISSUE TITLE
Package-list-view automatically switches back to local from remote after installing a package

### ISSUE THREAD

**Issue by silvernode** [aarnt/octoxbps#1]
Steps to reproduce:

1. click remote repository icon
2. Search for a package
3. Install a package

After the package has installed, the package list frame automatically switches back to local package view.

This seems like a bug, but I'm not sure.  I would expect the remote icon to stay highlighted until I decide otherwise.

**Comment by aarnt** [comment]
It was intended.
But in the 0.2.0 version (which is being developed), the package list now shows non-installed packages too.
