### ISSUE TITLE
Command finished with errors!

### ISSUE THREAD

**Issue by hervyqa** [aarnt/octoxbps#11]
No error but this octoxbps said error notif.

![Screenshot_20201005_171012](https://user-images.githubusercontent.com/45872139/95067829-92efa100-072e-11eb-821c-6a0948d1753d.png)

**Comment by aarnt** [comment]
I could not reproduce the error.
Is it still happening? Which SO? Void or Trident?
Which libc?

**Comment by hervyqa** [comment]
@aarnt voidlinux. musl libc.

**Comment by aarnt** [comment]
@hervyqa 
That's probably a xbps issue.

Try opening a terminal and syncinc databases there and after the command has finished, just do a "echo $?" to retrieve command exit code.

**Comment by hervyqa** [comment]
somehow, it's fixed now.

**Comment by hervyqa** [comment]
Sorry @aarnt, I reopened the issue.

it turns out the message "command finished with error" only exists in `x86_64-musl` (even though there's actually nothing wrong with it). While I try on `x86_64` there is no error message.
