### ISSUE TITLE
OctoXBPS not detecting specific shells

### ISSUE THREAD

**Issue by nbmlx** [aarnt/octoxbps#12]
Hello I just want to notify a little "warning" that I'm receiving when installing packages using OctoXBPS.

`read illegal option -n`

![2020-12-08-125437_3840x1080_scrot](https://user-images.githubusercontent.com/69022037/101507057-e6f84b00-3954-11eb-9b87-98ae72d2c17e.png)

It has to do with the program not detecting the specific shell I'm using (in this case mksh). I know it's not a huge problem but could be fixed easily.

One solution could be that temporary installation scripts (`.qt_temp_*`) get executed using bash (with a shebang in the script) or maybe simple dash?

I'm really liking OctoXBPS, thx for the work 😀

**Comment by aarnt** [comment]
Hi @nbmlx 
Could you test latest devel code?

**Comment by nbmlx** [comment]
I'll get back with results once I update some package.

**Comment by aarnt** [comment]
If you try to install/remove a pkg using the terminal option you may ser the error too.

**Comment by nbmlx** [comment]
It's working perfectly, no errors raised at all with the git compiled version when I updated packages. Just for more info, the terminal showed `sudo bash -c` after entering the password. Thanks Aarnt.

**Comment by aarnt** [comment]
Nice. So can It be closed?

**Comment by nbmlx** [comment]
Yes sure.
