### ISSUE TITLE
Dark theme ?

### ISSUE THREAD

**Issue by sspade1** [aarnt/octoxbps#17]
Please tell us how did you get a dark theme for octoxbps.
I run Gnome40 and I use the theme Mojave-dark.
Regards

**Comment by aarnt** [comment]
Hi @sspade1 

You have to put 

`QT_QPA_PLATFORMTHEME=qt5ct`

In your preferred file (here in ArcoLinux I use /etc/environment).

Then, open your "qt5ct" program (yes, you have to install it) and on the Appearence tab, choose "Custom" (Pallete Group) and select a theme you like.
