### ISSUE TITLE
octoxbps as root ?

### ISSUE THREAD

**Issue by cr6void** [aarnt/octoxbps#2]
**EDITED**

Hello @aarnt ,

I currently use octoxbps in [Void linux](http://www.voidlinux.eu/)

When I try to run the program as root:
`$ sudo octoxbps`
I see this message: "You can not run octoXBPS with administrator's credential."

Now when I run the program as a regular user:
`$ octoxbps`
I can start it.
But when I want to install / remove a package, I see this error: "There are no means to get administrator's credentials. You'll need to install a su frontend like gksu or kdesu."

I can't use your program without gksu / kdesu.
Why ?
It doesn't make sense for me...
...**but if everyone thinks it's okay, well, I guess I'm wrong.** :wink:

Regards.

**Comment by AngryPhantom** [comment]
Sorry, but why is this issue closed without any explanation? I installed Void and really love it, but would like to use GUI for xbps! Unfortunately I can't google any solution for that...

**Comment by mobinmob** [comment]
@AngryPhantom : Just install octoxbps and kdesu and use the program... it is working.

**Comment by AngryPhantom** [comment]
@mobinmob Sorry but I'm using XFCE and I don't need one fifth of KDE... Anyway, thank you for response. I guess it's impossible to use this nice GUI tool.

**Comment by aarnt** [comment]
Hi @AngryPhantom 
You can use git version as upstream does not need kde anymore. It has its own sudo gui tool.

**Comment by AngryPhantom** [comment]
@aarnt
Thank you. Well, they say "You'll need "git" and "qt5" packages in order to get latest dev version":

> sudo xbps-install qt5-devel 
> nvidia340-340.108_3: broken, unresolvable shlib `libnvidia-ml.so.1'
> Transaction aborted due to unresolved shlibs.

Fresh Void install with XFCE + nvidia340

**Comment by aarnt** [comment]
@AngryPhantom 
Maybe you have to try just qt5 not the devel pkg.

**Comment by mobinmob** [comment]
@aarnt: Making a release will be really nice. I have a working template locally for current master but I cannot submit a PR as it will not be accepted without a release.

**Comment by AngryPhantom** [comment]
@aarnt 
That's what is already installed. Probably when I installed qt5ct (for Qt Apps to look like Gtk):
Then I installed qt5-qmake as required to compile octoxbps.

```
[*] qt5-5.14.2_3
[*] qt5-concurrent-5.14.2_3
[*] qt5-core-5.14.2_3
[*] qt5-dbus-5.14.2_3
[*] qt5-declarative-5.14.2_3
[*] qt5-gui-5.14.2_3
[*] qt5-network-5.14.2_3
[*] qt5-opengl-5.14.2_3
[*] qt5-printsupport-5.14.2_3
[*] qt5-qmake-5.14.2_3
[*] qt5-sql-5.14.2_3
[*] qt5-svg-5.14.2_3
[*] qt5-test-5.14.2_3
[*] qt5-wayland-5.14.2_3
[*] qt5-widgets-5.14.2_3
[*] qt5-x11extras-5.14.2_3
[*] qt5-xml-5.14.2_3
[*] qt5ct-0.41_1
[*] qtchooser-66_1
```

**Comment by AngryPhantom** [comment]
Anyway, I've posted an [issue](https://github.com/void-linux/void-packages/issues/21993) on Void also.

**Comment by AngryPhantom** [comment]
Looks like there is a [problem](https://github.com/void-linux/void-packages/issues/21993#issuecomment-629440513) in Void's metapackages.
