### ISSUE TITLE
rcc: not found

### ISSUE THREAD

**Issue by ThePademelon** [aarnt/octoxbps#21]
I'm trying to compile octoxbps but I seem to be missing an SDK or something. I'm on Void Linux, what xbps package should I install to remedy this?

```
[nim@pc-gamma sudo]$ qmake-qt5
Info: creating stash file /home/nim/repositories/octoxbps/sudo/.qmake.stash
sh: 1: /usr/lib/qt5/bin/rcc: not found
sh: 1: /usr/lib/qt5/bin/uic: not found
[nim@pc-gamma sudo]$ 
```

Thanks!

**Comment by b-cpu** [comment]
qt5-host-tools

**Comment by ThePademelon** [comment]
Thanks! I hit another problem after that but I just installed qtcreator-full and that seemed to have everything needed for compilation.
