### ISSUE TITLE
OctoXBPS always prompts for password on start

### ISSUE THREAD

**Issue by dexgs** [aarnt/octoxbps#23]
Every time OctoXBPS is started, it displays a password prompt in order to authenticate running `xbps-install -Syy` to synchronize the local and remote package databases. It is my understanding that it is only meant to show this prompt if it cannot find `pkgdb*.plist` in `/var/db/xbps`, so it seems like showing this prompt every time the program starts is not intended.

**Comment by dexgs** [comment]
I've identified the cause of the issue. OctoXBPS only checks for the existence of `pkgdb*.plist` in `var/db/xbps` if it decides that it is running on Void Linux or Trident Linux. It detects Void Linux based on whether or not the string, `PRETTY_NAME="void"` occurs in `/etc/os-release`. However, Void Linux recently changed this file and it now contains `PRETTY_NAME="Void Linux"` instead.

**Comment by dexgs** [comment]
Here is the commit in which the change is made: https://github.com/void-linux/void-packages/commit/1dfc401d1237120e8e936627e7e28d2441916e80

**Comment by dexgs** [comment]
I have opened a pull request which resolves the issue: https://github.com/aarnt/octoxbps/pull/24

**Comment by aarnt** [comment]
Merged pull request. Thanks!
