### ISSUE TITLE
Failed to exec 'sudo': No such file or directory

### ISSUE THREAD

**Issue by haheute** [aarnt/octoxbps#30]
When trying to sync the database manually (in the main window of OctoXBPS), I get this error message: 
```
Synchronizing databases...

octoxbps-sudo: Failed to exec 'sudo': No such file or directory

Command finished with errors!
```
I don't have sudo installed, only doas (Void Linux). I thought it would work with doas, too, but I'm not sure.

The files `/usr/bin/doas` and `/etc/doas.conf` seem to exist:
```
ls -al /usr/bin/doas
-rwsr-xr-x 1 root root 43168 26. Jan 2022  /usr/bin/doas
ls -al /etc/doas.conf   
-rw-r--r-- 1 root root 23 13. Feb 2021  /etc/doas.conf
```

**Comment by aarnt** [comment]
@haheute 
Hmm, that's weird.
Here I can use doas and/or sudo without any problem. Same path as yours.

**Comment by haheute** [comment]
Do you have sudo installed?  I have uninstalled it and have only doas.

**Comment by aarnt** [comment]
Hmm,ok. I'll test this setup, then.

**Comment by haheute** [comment]
Sorry I didn't see your edit ...
I had followed this part of the documentation: https://docs.voidlinux.org/xbps/advanced-usage.html#ignoring-packages
No problem.. I just reported it and thought maybe it is a bug or so .. thanks anyway

**Comment by haheute** [comment]
![octo-bug_2022-10-20_20-41-17](https://user-images.githubusercontent.com/5753419/197031467-e1e3e832-2590-43d2-87db-7e44ad6448df.jpg)

this is what I see..
maybe something is wrong with my setup... not sure what...

**Comment by aarnt** [comment]
> Sorry I didn't see your edit ... I had followed this part of the documentation: https://docs.voidlinux.org/xbps/advanced-usage.html#ignoring-packages No problem.. I just reported it and thought maybe it is a bug or so .. thanks anyway

Alright, I'll try that removal, then.

**Comment by aarnt** [comment]
Well, it seems sudo is now a required package due to base-system.

**Comment by haheute** [comment]
I believe it was required, all the time. That is the reason why this "[ignore package](https://docs.voidlinux.org/xbps/advanced-usage.html#ignoring-packages)" needed to be done, as in the one post above. Without that, it was not possible to uninstall sudo.

**Comment by haheute** [comment]
It works now. thanks  :+1:
