### ISSUE TITLE
v0.3.1: notifier now asking for password when checking for updates in the background.

### ISSUE THREAD

**Issue by gc-user** [aarnt/octoxbps#36]
After updating octoxbps on Void from v0.3.0_4 to v0.3.1_1 the notifier is asking for a password before checking for updates in the background (= syncing the database). That never happened in previous versions.

As the template for this package on the void packages github doesn't seem to have changed other than adjusting the version number, the source url and the hash, I would assume it's in the code itself, hence I post the bug report here. Unless, of course, some dependency changed, but that change isn't reflected in the template.

I use the notifier only as an indicator for available updates, and the terminal for updating. So, I never get asked for a password by the notifier. Until v0.3.1. That's why I noticed the change immediately.

For now, I downgraded to v0.3.0 to avoid this issue.

**Comment by aarnt** [comment]
@gc-user 
Thanks for opening the issue. It was my mistake. Will revert ASAP.

**Comment by aarnt** [comment]
Done.
https://github.com/aarnt/octoxbps/releases/tag/v0.3.2

**Comment by gc-user** [comment]
Can confirm the bug is gone in v0.3.2. (Self-compiled, using the (adjusted) template of v0.3.1.)
Thanks again!
