### ISSUE TITLE
More question than bug report: Synchronizing database via notifier tray icon vs via octoxbps program window

### ISSUE THREAD

**Issue by gc-user** [aarnt/octoxbps#39]
I noticed long ago that I have to enter a password if I want to synchronize the database in the octoxbps program window. Only the recent issues with the notifier made me aware that this isn't the case with synchronizing the database using the notifier.

So, now I'm wondering if that is deliberate and if so what reason behind that is - or, if it is not deliberate, if it can be fixed.

**Comment by aarnt** [comment]
Hi @gc-user 

It's deliberate. A notifier should never ask for a password.
But for the main app, you need to customize your sudo config to achieve a nopasswd xp.

**Comment by gc-user** [comment]
Thanks for the clarification. I'll just leave it like it is.
