### ISSUE TITLE
Feature request: Allow custom locations for xbps-install & xbps-remove utilities

### ISSUE THREAD

**Issue by akarelas** [aarnt/octoxbps#41]
Since I'm using the `etckeeper` utility, which keeps git commits of changes in the `/etc` directory, I wrapped the `xbps-install` and `xbps-remove` programs with my own scripts with the same name, placed them in the /usr/local/bin directory, so that they execute the etckeeper pre-install and post-install scripts (a necessary move, as xbps does not support hooks) when I run xbps-install/remove from the console.

This setup works fine when when using the command-line, but unfortunately doesn't when I use octoxbps and octoxbps-notifier to install/remove packages or to update my system, because octoxbps is executing the specific xbps-{install,remove} scripts that are under /usr/bin.

Would it be possible for you to remove the directory /usr/bin from the execution of the xbps utilities, so that they are searched from `$PATH`? This way we can create custom versions of xbps-{install,remove} and all will be fine. Alternatively, if my first suggestion is not possible, then could you please allow the overriding of these locations with environment variables?

Thanks.

**Comment by aarnt** [comment]
Hi.
Searching first for xbps tools on "/usr/local/bin" and use this path if so solves your issue, doesn't it?

**Comment by akarelas** [comment]
This doesn't seem like a perfect solution, because other users might want to place their wrapper scripts in their `/root/.bin` directory. You'd have to search for that too, perhaps. And you'd have to know the order of directories in the `$PATH` variable (maybe the user modified it).

Isn't it better just to remove the path from the execution command?

**Comment by aarnt** [comment]
I'm sorry but removing the full path is too risky, because a malicious program could harm the system as it'll be executed with elevated privileges.

**Comment by akarelas** [comment]
I'd be happy with this solution then:

> Searching first for xbps tools on "/usr/local/bin" and use this path if so solves your issue, doesn't it?

**Comment by aarnt** [comment]
Hi @akarelas 
Yesterday I coded the changes and were able to add a nice pre system upgrade hook using a custom posix shell wrapper on /usr/local/bin. Can you test your solution using latest git code?

**Comment by akarelas** [comment]
I don't know how to do that. Do you mean xbps-src? I've used that once, I'll try if you want (and I might ask you or on IRC for help in doing that).

**Comment by akarelas** [comment]
Ah, THIS git repo. Okay.

**Comment by akarelas** [comment]
If I follow the steps on this page to install octoxbps from source, how easy will it be afterwards to cleanup everything? (And how will I do it?) I don't want it to mess my system.

**Comment by aarnt** [comment]
Well, if you do not have the qt dev tools, maybe it's better if I tag a release and you upgrade octoxbps using the official method.

**Comment by akarelas** [comment]
Yes, thanks!

**Comment by aarnt** [comment]
> Yes, thanks!

I've just released v0.4.0. Let's wait for XBPS automated package updates.

**Comment by akarelas** [comment]
great news!

**Comment by akarelas** [comment]
By no means an expert, but shouldn't there be a PR here? https://github.com/void-linux/void-packages/pulls?q=is%3Apr+octoxbps

**Comment by aarnt** [comment]
Probably...

**Comment by akarelas** [comment]
I noticed all of these PRs were made by people other than you. Should someone who is interested, other than you, do this one too?

**Comment by akarelas** [comment]
Or should it happen automatically by a bot?

**Comment by aarnt** [comment]
Indeed, it was never me. But this time it's taking a while.

**Comment by aarnt** [comment]
@akarelas 
It seems we are close to something...
https://repo-default.voidlinux.org/void-updates/void-updates.txt shows octoxbps 0.4.0 is scheduled...

**Comment by akarelas** [comment]
Not that close yet, it seems :D Almost a month passed

**Comment by akarelas** [comment]
Any idea what they're waiting for?

**Comment by aarnt** [comment]
No... I tried to contact another dev but he didn't reply me either.

**Comment by aarnt** [comment]
Hi, it seems they finally updated the pkg. Can you test it?

**Comment by akarelas** [comment]
My void laptop's pretty broken. I'll try when I get home (which doesn't happen much though).

**Comment by aarnt** [comment]
Ok. I will close this issue as it is fixed (at least for me).

**Comment by akarelas** [comment]
My laptop is being repaired for the next 3 weeks.

**Comment by akarelas** [comment]
I just tried my repaired laptop for the first time, and am happy to announce that my feature suggestion has been implemented successfully. Thanks!w
