### ISSUE TITLE
search doesn't find all it could

### ISSUE THREAD

**Issue by chriscamacho** [aarnt/octoxbps#5]
~]$ xbps-query -Rs game | wc -l
140

if I type game into octoxbps find dialog it only finds 13 packages, I believe this because its not looking in the package descriptions

octoxbps would be much more useful if the search included the description

**Comment by ernierasta** [comment]
Hi! You can search in description, just choose it from menu:

Search - By description.

Tested it, result is as you expected.

**Comment by chriscamacho** [comment]
so you can, completely missed that...
