### ISSUE TITLE
command errors with certain su frontends

### ISSUE THREAD

**Issue by Quantroup** [aarnt/octoxbps#7]
**Problem**: When trying to refresh databases, update or anything that requires su or sudo access; some su frontends (lxqt-sudo in this instance) instead of running the program it uses the bash exec command, causing an error

`bash: line 0: exec: xbps-install -Syy: not found` 

**How to replicate**: using the lxqt-sudo package as a frontend for su, refresh databases or install updates

**Misc. information**: 
OctoXBPS - 0.2.2 (Qt 5.11.3)

XBPS: 0.59.1 API: 20200221 GIT: UNSET

**Comment by aarnt** [comment]
@Quantroup 
If you could, please use upstream code.
There is an "embedded" sudo tool now called "octoxbps-sudo".

**Comment by Vistaus** [comment]
The tool doesn't seem to have been added as Octoxbps reports that it can't find it. The compilation output doesn't show any errors whatsoever.

**Comment by mobinmob** [comment]
The contents of the octoxbps-package are the following:
```
/etc/polkit-1/rules.d/49-nopasswd_limited_xbps_install_sync.rules
/usr/bin/octoxbps
/usr/bin/octoxbps-notifier
/usr/lib/octoxbps/octoxbps-sudo
/usr/share/applications/octoxbps-notifier.desktop
/usr/share/applications/octoxbps.desktop
/usr/share/icons/octopi.png
/usr/share/polkit-1/actions/org.freedesktop.policykit.pkexec.run-xbpsinstall.policy
```
octoxbps-sudo is there :)
