### ISSUE TITLE
LANG env variable ?

### ISSUE THREAD

**Issue by vttfreebsd** [aarnt/octoxbps#9]
Hello,
It's seemed that octoxbps doesn't take in account the LANG env variable when launching xbps-install.
I've checked that with grub-mkconfig.
grub-mkconfig uses LANG to make a locale version of /boot/grub/grub.cfg. When grub-mkconfig is launched by octoxbps, it creates a US version of grub.cfg
Is there a solution for that ?
Thx for reading
vTT

**Comment by aarnt** [comment]
@vttfreebsd 
Indeed it does not. The parser needs en_US to function correctly.
